name: core_kosmos
description: A new Flutter package project.
version: 1.1.0
homepage:

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_screenutil: ^5.9.3
  responsive_framework: ^1.5.1
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: