name: twogather
description: 2Gather application.

publish_to: 'none'

version: 0.0.6+6

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  ############
  # Firebase #
  ############
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7

  cloud_functions: ^5.6.2
  firebase_messaging: ^15.2.7
  firebase_database: ^11.3.10

  ###########
  # Google Sign In #
  ###########
  google_sign_in: ^6.3.0

  ###########
  # Apple Sign In #
  ###########
  sign_in_with_apple: ^7.0.1

  ###########
  # Freezed #
  ###########
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1

  ##############
  # Auto_Route #
  ##############
  auto_route: ^9.3.0+1

  ####################
  # Riverpod & Hooks #
  ####################
  hooks_riverpod: ^2.6.1

  ##########
  # Get_it #
  ##########
  get_it: ^8.0.2

  #######
  # Get #
  #######
  get: ^4.6.6

  #########
  # Dartz #
  #########
  dartz: ^0.10.1

  ##############
  # Responsive #
  ##############
  responsive_framework: ^1.5.1
  flutter_screenutil: ^5.9.3

  ###############
  # Translating #
  ###############
  easy_localization: ^3.0.8

  flutter_native_splash: ^2.4.6
  expandable_page_view: ^1.0.17
  flutter_svg: ^2.2.1
  flutter_typeahead: ^5.0.1
  image_picker: ^1.1.3
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.5
  share_plus: ^12.0.0
  timeago: ^3.7.0
  localstorage: ^4.0.0+1
  sliding_up_panel: ^2.0.0+1
  flutter_staggered_animations: ^1.0.0
  shimmer: ^3.0.0
  badges: ^3.1.2
  cupertino_will_pop_scope: ^1.2.1
  flutter_slidable: ^4.0.1
  flutter_rating_bar: ^4.0.0
  iconsax: ^0.0.8
  flutter_isolate: ^2.0.0
  intl: ^0.20.2
  http: ^1.2.3
  rxdart: ^0.27.7
  image: ^4.5.4
  readmore: ^2.1.0
  bubble: ^1.2.1
  flutter_blurhash: ^0.9.1
  font_awesome_flutter: ^10.10.0
  wechat_assets_picker: ^9.3.2
  wechat_camera_picker: ^4.3.3
  flutter_lints: ^6.0.0
  flutter_riverpod: ^2.6.1
  crop_your_image: ^2.0.0
  lottie: ^3.3.2
  flutter_cache_manager: ^3.4.1
  uuid: ^4.5.1
  dio: ^5.7.0
  chewie: ^1.13.0
  video_player: ^2.9.2
  intrinsic_grid_view: ^0.0.2
  animated: ^2.0.0
  timeago_flutter: ^3.7.0
  tab_indicator_styler: ^2.0.0
  hsv_color_pickers: ^0.4.0
  painter: ^2.0.0
  zoom_widget: ^2.0.1
  scrollable_positioned_list: ^0.3.8
  fluttertoast: ^8.2.14
  path: ^1.9.0
  vector_math: ^2.1.4

  ##################
  # Kosmos Package #
  ##################

  core_kosmos:
    path: package/package-core

  ui_kosmos_v4:
    path: package/package-ui-kosmos

  form_generator_kosmos:
    path: package/package-form-generator

  skeleton_kosmos:
    path: package/responsive-skeleton

  permissionrequest:
    path: package/permissionrequest

  form_kosmos:
    path: package/package-form

  settings_kosmos:
    path: package/package-responsive-settings

  auth_helper:
    path: package/firebase_auth_kosmos

  flutter_localizations:
    sdk: flutter

  flutter_keyboard_visibility: ^6.0.0
  permission_handler: ^12.0.0+1
  blurhash_dart: ^1.1.0
  flutter_local_notifications: ^19.4.2
  timelines_plus: ^1.0.0
  shared_preferences: ^2.5.3
  vibration: ^3.1.4

dev_dependencies:

  build_runner: ^2.5.4
  freezed: ^2.5.8
  auto_route_generator: ^9.3.1
  visibility_detector: ^0.4.0+2
  json_serializable: ^6.9.5

  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: assets/images/img_logo.png
  android_12: 
    android: false
    ios: false
    android_gravity: center
    ios_content_mode: scaleAspectFit

flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  
  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - assets/png/
    - assets/json/
    - assets/translations/
    - assets/images/example/