name: ui_kosmos_v4
description: A new Flutter package project.
version: 1.0.4
homepage: none
publish_to: 'none'

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  datetime_picker_formfield: ^2.0.1
  intl: ^0.20.2
  intl_phone_number_input: ^0.7.4
  flutter_svg: ^2.0.10+1
  iconsax: ^0.0.8
  fluttertoast: ^8.2.13
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  hooks_riverpod: ^2.6.1
  file_picker: ^8.1.4
  easy_localization: ^3.0.1

  core_kosmos:
    path: ../package-core
  image_picker: ^1.1.3
  flutter_hooks: ^0.20.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
