name: form_kosmos
description: A new Flutter package project.
version: 0.0.1
homepage: none
publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.5.0


  ####################
  # Riverpod & Hooks #
  ####################
  hooks_riverpod: ^2.6.1

  ###############
  # Translating #
  ###############
  easy_localization: ^3.0.8

  ##########
  # Get_it #
  ##########
  get_it: ^8.0.2

  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  expandable_page_view: ^1.0.13
  image_picker: ^1.1.3
  cached_network_image: ^3.4.1

  #################
  # Flutter Toast #
  #################
  fluttertoast: ^8.2.8

  ##################
  # Kosmos Package #
  ##################
  core_kosmos:
    path: ../package-core

  ui_kosmos_v4:
    path: ../package-ui-kosmos

  form_generator_kosmos:
    path: ../package-form-generator

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
