// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRyrzpkYx9NqgglE6h8AQN1uLq6Mw5ueY',
    appId: '1:832813741534:android:e1e41d0d9e7444955fd94f',
    messagingSenderId: '832813741534',
    projectId: 'gather-10f2b',
    storageBucket: 'gather-10f2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW1b0XnEQnND1gv5H6K6kGbRStbMwYO-Y',
    appId: '1:832813741534:ios:c3dd5d48a110baf65fd94f',
    messagingSenderId: '832813741534',
    projectId: 'gather-10f2b',
    storageBucket: 'gather-10f2b.firebasestorage.app',
    androidClientId:
        '832813741534-bn4j3foirub4k2rv96k6ogpbe1h7o799.apps.googleusercontent.com',
    iosClientId:
        '832813741534-hbdfbvsn369u6m6jaoem2ef96cqm6445.apps.googleusercontent.com',
    iosBundleId: 'com.twogather.app',
  );
}
