name: skeleton_kosmos
description: A new Flutter package project.
version: 3.2.0
publish_to: "none"
homepage: none

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ############
  # Firebase #
  ############
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  cloud_functions: ^5.6.2
  firebase_storage: ^12.4.7
  firebase_messaging: ^15.2.7


  ###########
  # Google Sign In #
  ###########
  google_sign_in: ^6.3.0

  ###########
  # Apple Sign In #
  ###########
  sign_in_with_apple: ^7.0.1

  country_picker: ^2.0.16

  ##########
  # G Maps #
  ##########
  google_maps_flutter: ^2.13.1

  ##########
  # Stripe #
  ##########
  # flutter_stripe: ^3.3.0
  # stripe_checkout: ^1.0.0

  ##################
  # Location & Map #
  ##################
  geolocator: ^14.0.1
  # geoflutterfire: ^3.0.2  # Remplacé par GeolocationService natif

  ###########
  # Freezed #
  ###########
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  ###############################
  # Auto_Route And Url handling #
  ###############################
  auto_route: ^9.3.0+1
  url_strategy: ^0.2.0

  ####################
  # Riverpod & Hooks #
  ####################
  hooks_riverpod: ^2.6.1

  ##########
  # Get_it #
  ##########
  get_it: ^8.0.2

  #######
  # Get #
  #######
  get: ^4.6.6

  #########
  # Dartz #
  #########
  dartz: ^0.10.1

  ##############
  # Responsive #
  ##############
  responsive_framework: ^1.5.1
  flutter_screenutil: ^5.9.3

  ###############
  # Translating #
  ###############
  easy_localization: ^3.0.8

  ################
  # Universal IO #
  ################
  universal_io: ^2.0.4

  #################
  # Flutter Toast #
  #################
  fluttertoast: ^8.2.8

  ########
  # Path #
  ########
  path: ^1.9.0

  cached_network_image: ^3.3.1
  # image_picker_web: ^2.1.1
  image_picker: ^1.1.3
  flutter_svg: ^2.0.10+1
  http: ^1.2.3
  mime_type: ^1.0.0
  expandable_page_view: ^1.0.17
  url_launcher: ^6.1.5
  pin_code_fields: ^8.0.1
  sliding_up_panel: ^2.0.0+1
  localstorage: ^4.0.0+1
  shared_preferences: ^2.5.3
  ##################
  # Kosmos Package #
  ##################
  core_kosmos:
    path: ../package-core

  ui_kosmos_v4:
    path: ../package-ui-kosmos

  form_generator_kosmos:
    path: ../package-form-generator
  
  settings_kosmos:
    path: ../package-responsive-settings
  
  auth_helper:
    path: ../firebase_auth_kosmos
  
  permissionrequest:
    path: ../permissionrequest
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  assets:
    - assets/fonts/
    - assets/images/
