name: auth_helper
description: A new Flutter package project.
version: 1.0.2
homepage: none
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.9
  easy_localization: ^3.0.8
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  http: ^1.2.3
  tuple: ^2.0.2
  crypto: ^3.0.2
  pin_code_fields: ^8.0.1

  ui_kosmos_v4:
    path: ../package-ui-kosmos

  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
