name: form_generator_kosmos
description: A new Flutter package project.
version: 1.1.0
homepage: none
publish_to: 'none'

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^8.1.4
  image_picker: ^1.1.3
  
  ui_kosmos_v4:
    path: ../package-ui-kosmos
  core_kosmos:
    path: ../package-core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
